# Dependencies
highlighter:         rouge
gems: [jekyll-paginate]

# Permalinks
permalink:        pretty

# Setup
title:            Laura Pickens
tagline:          'Cybersecurity Analyst'
description:      'Personal blog documenting research/projects done by Laura.'
url:              https://www.laurapickens.net
enforce_ssl:      www.laurapickens.net
baseurl:          /

author:
  name:           'Laura Pickens'
  url:            //twitter.com/pickl09

paginate:         5

collections:
  books:
    output: true

# Set excerpt separator
truncate_size:    70

# Custom vars
version:          2.0.0

github:
  repo:           //github.com/pickl09

# Social networking links used in footer. Update and remove as you like.
  twitter:        //twitter.com/pickl09
  facebook:       
  linkedin:       
